//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Project2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarteDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class CarteDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.AutorDTO AutorDtoField;
        
        private WCF_Project2.GenDTO GenDtoField;
        
        private WCF_Project2.ImprumutDTO[] ImprumutDtoField;
        
        private int autorIdField;
        
        private int carteIdField;
        
        private int genIdField;
        
        private string titluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.AutorDTO AutorDto
        {
            get
            {
                return this.AutorDtoField;
            }
            set
            {
                this.AutorDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.GenDTO GenDto
        {
            get
            {
                return this.GenDtoField;
            }
            set
            {
                this.GenDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.ImprumutDTO[] ImprumutDto
        {
            get
            {
                return this.ImprumutDtoField;
            }
            set
            {
                this.ImprumutDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int autorId
        {
            get
            {
                return this.autorIdField;
            }
            set
            {
                this.autorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carteId
        {
            get
            {
                return this.carteIdField;
            }
            set
            {
                this.carteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genId
        {
            get
            {
                return this.genIdField;
            }
            set
            {
                this.genIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titlu
        {
            get
            {
                return this.titluField;
            }
            set
            {
                this.titluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class AutorDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.CarteDTO[] CarteDtoField;
        
        private int autorIdField;
        
        private string numeField;
        
        private string prenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.CarteDTO[] CarteDto
        {
            get
            {
                return this.CarteDtoField;
            }
            set
            {
                this.CarteDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int autorId
        {
            get
            {
                return this.autorIdField;
            }
            set
            {
                this.autorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume
        {
            get
            {
                return this.numeField;
            }
            set
            {
                this.numeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenume
        {
            get
            {
                return this.prenumeField;
            }
            set
            {
                this.prenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class GenDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.CarteDTO[] CarteDtoField;
        
        private string descriereField;
        
        private int genIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.CarteDTO[] CarteDto
        {
            get
            {
                return this.CarteDtoField;
            }
            set
            {
                this.CarteDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descriere
        {
            get
            {
                return this.descriereField;
            }
            set
            {
                this.descriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genId
        {
            get
            {
                return this.genIdField;
            }
            set
            {
                this.genIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImprumutDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class ImprumutDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.CarteDTO CarteDtoField;
        
        private WCF_Project2.CititorDTO CititorDtoField;
        
        private WCF_Project2.ReviewDTO[] ReviewField;
        
        private int carteIdField;
        
        private int cititorIdField;
        
        private System.Nullable<System.DateTime> dataImprumutField;
        
        private System.Nullable<System.DateTime> dataRestituireField;
        
        private System.Nullable<System.DateTime> dataScadentaField;
        
        private int imprumutIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.CarteDTO CarteDto
        {
            get
            {
                return this.CarteDtoField;
            }
            set
            {
                this.CarteDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.CititorDTO CititorDto
        {
            get
            {
                return this.CititorDtoField;
            }
            set
            {
                this.CititorDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.ReviewDTO[] Review
        {
            get
            {
                return this.ReviewField;
            }
            set
            {
                this.ReviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carteId
        {
            get
            {
                return this.carteIdField;
            }
            set
            {
                this.carteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cititorId
        {
            get
            {
                return this.cititorIdField;
            }
            set
            {
                this.cititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataImprumut
        {
            get
            {
                return this.dataImprumutField;
            }
            set
            {
                this.dataImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataRestituire
        {
            get
            {
                return this.dataRestituireField;
            }
            set
            {
                this.dataRestituireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataScadenta
        {
            get
            {
                return this.dataScadentaField;
            }
            set
            {
                this.dataScadentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int imprumutId
        {
            get
            {
                return this.imprumutIdField;
            }
            set
            {
                this.imprumutIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CititorDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class CititorDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.ImprumutDTO[] ImprumutDtoField;
        
        private string adresaField;
        
        private int cititorIdField;
        
        private string emailField;
        
        private string numeField;
        
        private string prenumeField;
        
        private System.Nullable<short> stareField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.ImprumutDTO[] ImprumutDto
        {
            get
            {
                return this.ImprumutDtoField;
            }
            set
            {
                this.ImprumutDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresa
        {
            get
            {
                return this.adresaField;
            }
            set
            {
                this.adresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cititorId
        {
            get
            {
                return this.cititorIdField;
            }
            set
            {
                this.cititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume
        {
            get
            {
                return this.numeField;
            }
            set
            {
                this.numeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenume
        {
            get
            {
                return this.prenumeField;
            }
            set
            {
                this.prenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> stare
        {
            get
            {
                return this.stareField;
            }
            set
            {
                this.stareField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project2")]
    public partial class ReviewDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCF_Project2.ImprumutDTO ImprumutDtoField;
        
        private int imprumutIdField;
        
        private int reviewIdField;
        
        private string textField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Project2.ImprumutDTO ImprumutDto
        {
            get
            {
                return this.ImprumutDtoField;
            }
            set
            {
                this.ImprumutDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int imprumutId
        {
            get
            {
                return this.imprumutIdField;
            }
            set
            {
                this.imprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reviewId
        {
            get
            {
                return this.reviewIdField;
            }
            set
            {
                this.reviewIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBookService")]
public interface IBookService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BuyBooks", ReplyAction="http://tempuri.org/IBookService/BuyBooksResponse")]
    void BuyBooks(WCF_Project2.CarteDTO carteDto, short numberOfBooks);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BuyBooks", ReplyAction="http://tempuri.org/IBookService/BuyBooksResponse")]
    System.Threading.Tasks.Task BuyBooksAsync(WCF_Project2.CarteDTO carteDto, short numberOfBooks);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAvailableBooks", ReplyAction="http://tempuri.org/IBookService/GetAvailableBooksResponse")]
    WCF_Project2.CarteDTO[] GetAvailableBooks();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAvailableBooks", ReplyAction="http://tempuri.org/IBookService/GetAvailableBooksResponse")]
    System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetAvailableBooksAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBookById", ReplyAction="http://tempuri.org/IBookService/GetBookByIdResponse")]
    WCF_Project2.CarteDTO GetBookById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBookById", ReplyAction="http://tempuri.org/IBookService/GetBookByIdResponse")]
    System.Threading.Tasks.Task<WCF_Project2.CarteDTO> GetBookByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
    WCF_Project2.CarteDTO[] GetAllBooks();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
    System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetAllBooksAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooksByGen", ReplyAction="http://tempuri.org/IBookService/GetBooksByGenResponse")]
    WCF_Project2.CarteDTO[] GetBooksByGen(string gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooksByGen", ReplyAction="http://tempuri.org/IBookService/GetBooksByGenResponse")]
    System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetBooksByGenAsync(string gen);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBookServiceChannel : IBookService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BookServiceClient : System.ServiceModel.ClientBase<IBookService>, IBookService
{
    
    public BookServiceClient()
    {
    }
    
    public BookServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void BuyBooks(WCF_Project2.CarteDTO carteDto, short numberOfBooks)
    {
        base.Channel.BuyBooks(carteDto, numberOfBooks);
    }
    
    public System.Threading.Tasks.Task BuyBooksAsync(WCF_Project2.CarteDTO carteDto, short numberOfBooks)
    {
        return base.Channel.BuyBooksAsync(carteDto, numberOfBooks);
    }
    
    public WCF_Project2.CarteDTO[] GetAvailableBooks()
    {
        return base.Channel.GetAvailableBooks();
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetAvailableBooksAsync()
    {
        return base.Channel.GetAvailableBooksAsync();
    }
    
    public WCF_Project2.CarteDTO GetBookById(int id)
    {
        return base.Channel.GetBookById(id);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.CarteDTO> GetBookByIdAsync(int id)
    {
        return base.Channel.GetBookByIdAsync(id);
    }
    
    public WCF_Project2.CarteDTO[] GetAllBooks()
    {
        return base.Channel.GetAllBooks();
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetAllBooksAsync()
    {
        return base.Channel.GetAllBooksAsync();
    }
    
    public WCF_Project2.CarteDTO[] GetBooksByGen(string gen)
    {
        return base.Channel.GetBooksByGen(gen);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.CarteDTO[]> GetBooksByGenAsync(string gen)
    {
        return base.Channel.GetBooksByGenAsync(gen);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILoanService")]
public interface ILoanService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/LoanBook", ReplyAction="http://tempuri.org/ILoanService/LoanBookResponse")]
    void LoanBook(WCF_Project2.CarteDTO book, WCF_Project2.CititorDTO reader, System.DateTime loanDate, System.DateTime deadLine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/LoanBook", ReplyAction="http://tempuri.org/ILoanService/LoanBookResponse")]
    System.Threading.Tasks.Task LoanBookAsync(WCF_Project2.CarteDTO book, WCF_Project2.CititorDTO reader, System.DateTime loanDate, System.DateTime deadLine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/UpdateLoan", ReplyAction="http://tempuri.org/ILoanService/UpdateLoanResponse")]
    void UpdateLoan(WCF_Project2.ImprumutDTO imprumut);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/UpdateLoan", ReplyAction="http://tempuri.org/ILoanService/UpdateLoanResponse")]
    System.Threading.Tasks.Task UpdateLoanAsync(WCF_Project2.ImprumutDTO imprumut);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanByUserEmail", ReplyAction="http://tempuri.org/ILoanService/GetLoanByUserEmailResponse")]
    WCF_Project2.ImprumutDTO GetLoanByUserEmail(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanByUserEmail", ReplyAction="http://tempuri.org/ILoanService/GetLoanByUserEmailResponse")]
    System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanByUserEmailAsync(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanByUserId", ReplyAction="http://tempuri.org/ILoanService/GetLoanByUserIdResponse")]
    WCF_Project2.ImprumutDTO GetLoanByUserId(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanByUserId", ReplyAction="http://tempuri.org/ILoanService/GetLoanByUserIdResponse")]
    System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanByUserIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanForBookId", ReplyAction="http://tempuri.org/ILoanService/GetLoanForBookIdResponse")]
    WCF_Project2.ImprumutDTO GetLoanForBookId(int bookId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoanForBookId", ReplyAction="http://tempuri.org/ILoanService/GetLoanForBookIdResponse")]
    System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanForBookIdAsync(int bookId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILoanServiceChannel : ILoanService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoanServiceClient : System.ServiceModel.ClientBase<ILoanService>, ILoanService
{
    
    public LoanServiceClient()
    {
    }
    
    public LoanServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoanServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void LoanBook(WCF_Project2.CarteDTO book, WCF_Project2.CititorDTO reader, System.DateTime loanDate, System.DateTime deadLine)
    {
        base.Channel.LoanBook(book, reader, loanDate, deadLine);
    }
    
    public System.Threading.Tasks.Task LoanBookAsync(WCF_Project2.CarteDTO book, WCF_Project2.CititorDTO reader, System.DateTime loanDate, System.DateTime deadLine)
    {
        return base.Channel.LoanBookAsync(book, reader, loanDate, deadLine);
    }
    
    public void UpdateLoan(WCF_Project2.ImprumutDTO imprumut)
    {
        base.Channel.UpdateLoan(imprumut);
    }
    
    public System.Threading.Tasks.Task UpdateLoanAsync(WCF_Project2.ImprumutDTO imprumut)
    {
        return base.Channel.UpdateLoanAsync(imprumut);
    }
    
    public WCF_Project2.ImprumutDTO GetLoanByUserEmail(string email)
    {
        return base.Channel.GetLoanByUserEmail(email);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanByUserEmailAsync(string email)
    {
        return base.Channel.GetLoanByUserEmailAsync(email);
    }
    
    public WCF_Project2.ImprumutDTO GetLoanByUserId(int id)
    {
        return base.Channel.GetLoanByUserId(id);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanByUserIdAsync(int id)
    {
        return base.Channel.GetLoanByUserIdAsync(id);
    }
    
    public WCF_Project2.ImprumutDTO GetLoanForBookId(int bookId)
    {
        return base.Channel.GetLoanForBookId(bookId);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.ImprumutDTO> GetLoanForBookIdAsync(int bookId)
    {
        return base.Channel.GetLoanForBookIdAsync(bookId);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IReaderService")]
public interface IReaderService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/GetReaderByEmail", ReplyAction="http://tempuri.org/IReaderService/GetReaderByEmailResponse")]
    WCF_Project2.CititorDTO GetReaderByEmail(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/GetReaderByEmail", ReplyAction="http://tempuri.org/IReaderService/GetReaderByEmailResponse")]
    System.Threading.Tasks.Task<WCF_Project2.CititorDTO> GetReaderByEmailAsync(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/RegisterReader", ReplyAction="http://tempuri.org/IReaderService/RegisterReaderResponse")]
    void RegisterReader(WCF_Project2.CititorDTO cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/RegisterReader", ReplyAction="http://tempuri.org/IReaderService/RegisterReaderResponse")]
    System.Threading.Tasks.Task RegisterReaderAsync(WCF_Project2.CititorDTO cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/IsReaderTrustworthy", ReplyAction="http://tempuri.org/IReaderService/IsReaderTrustworthyResponse")]
    bool IsReaderTrustworthy(WCF_Project2.CititorDTO cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReaderService/IsReaderTrustworthy", ReplyAction="http://tempuri.org/IReaderService/IsReaderTrustworthyResponse")]
    System.Threading.Tasks.Task<bool> IsReaderTrustworthyAsync(WCF_Project2.CititorDTO cititor);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IReaderServiceChannel : IReaderService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReaderServiceClient : System.ServiceModel.ClientBase<IReaderService>, IReaderService
{
    
    public ReaderServiceClient()
    {
    }
    
    public ReaderServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ReaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCF_Project2.CititorDTO GetReaderByEmail(string email)
    {
        return base.Channel.GetReaderByEmail(email);
    }
    
    public System.Threading.Tasks.Task<WCF_Project2.CititorDTO> GetReaderByEmailAsync(string email)
    {
        return base.Channel.GetReaderByEmailAsync(email);
    }
    
    public void RegisterReader(WCF_Project2.CititorDTO cititor)
    {
        base.Channel.RegisterReader(cititor);
    }
    
    public System.Threading.Tasks.Task RegisterReaderAsync(WCF_Project2.CititorDTO cititor)
    {
        return base.Channel.RegisterReaderAsync(cititor);
    }
    
    public bool IsReaderTrustworthy(WCF_Project2.CititorDTO cititor)
    {
        return base.Channel.IsReaderTrustworthy(cititor);
    }
    
    public System.Threading.Tasks.Task<bool> IsReaderTrustworthyAsync(WCF_Project2.CititorDTO cititor)
    {
        return base.Channel.IsReaderTrustworthyAsync(cititor);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IReviewService")]
public interface IReviewService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddReviewForLoan", ReplyAction="http://tempuri.org/IReviewService/AddReviewForLoanResponse")]
    void AddReviewForLoan(WCF_Project2.ImprumutDTO imprumut, string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddReviewForLoan", ReplyAction="http://tempuri.org/IReviewService/AddReviewForLoanResponse")]
    System.Threading.Tasks.Task AddReviewForLoanAsync(WCF_Project2.ImprumutDTO imprumut, string text);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IReviewServiceChannel : IReviewService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReviewServiceClient : System.ServiceModel.ClientBase<IReviewService>, IReviewService
{
    
    public ReviewServiceClient()
    {
    }
    
    public ReviewServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ReviewServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReviewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddReviewForLoan(WCF_Project2.ImprumutDTO imprumut, string text)
    {
        base.Channel.AddReviewForLoan(imprumut, text);
    }
    
    public System.Threading.Tasks.Task AddReviewForLoanAsync(WCF_Project2.ImprumutDTO imprumut, string text)
    {
        return base.Channel.AddReviewForLoanAsync(imprumut, text);
    }
}
